// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: gsloc/api/config/core/v1/tls.proto

package core

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TLS with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *TLS) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TLS with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in TLSMultiError, or nil if none found.
func (m *TLS) ValidateAll() error {
	return m.validate(true)
}

func (m *TLS) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetCertificatesUuid()) < 1 {
		err := TLSValidationError{
			field:  "CertificatesUuid",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return TLSMultiError(errors)
	}

	return nil
}

// TLSMultiError is an error wrapping multiple validation errors returned by
// TLS.ValidateAll() if the designated constraints aren't met.
type TLSMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TLSMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TLSMultiError) AllErrors() []error { return m }

// TLSValidationError is the validation error returned by TLS.Validate if the
// designated constraints aren't met.
type TLSValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TLSValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TLSValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TLSValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TLSValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TLSValidationError) ErrorName() string { return "TLSValidationError" }

// Error satisfies the builtin error interface
func (e TLSValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTLS.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TLSValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TLSValidationError{}
